version: '3.1'

services:
  db: 
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - '.:/app'
    environment:
      POSTGRES_DB: agent_zone
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  pgdata: